import {
  BOOK_ITEM,
  SERIES_RESOURSE_ITEM,
  SCIENCE_WORKS_ITEM,
  MULTI_VOLUME_BOOKS_ITEM,
  LEGIS_DOCUMENT_ITEM,
  STANDART_DESCRIPTION_ITEM,
  PART_OF_BOOK_ITEM,
  LANGUAGE_UA,
  LANGUAGE_EN,
  LANGUAGE_RU,
  SIGNS_FOR_UA,
  SIGNS_FOR_EN,
  SIGNS_FOR_RU,
  THESIS_ITEM,
  ABSTRACT_THESIS_ITEM,
  PAPER_FROM_MAGAZINE_ITEM,
  PAPER_FROM_BOOK_ITEM,
  PAPER_FROM_VOLUME_ITEM,
  PAPER_FROM_NEWSPAPER_ITEM,
  PAPER_FROM_SCIENCE_WORKS_ITEM,
  LOCAL_ELECTRONIC_ITEM,
  REMOTE_ELECTRONIC_ITEM,
  WEBSITE_ITEM,
  PAGE_FROM_WEBSITE_ITEM,
  INTERNET_PORTAL_ITEM,
  YEARBOOKS_ITEM,
  TYPICAL_PROJECT_ITEM,
  PRICE_LIST_ITEM,
  POSTCARD_ITEM,
  INTERVIEW_ITEM,
  CATALOGS_ITEM,
  CONSTRUCTION_RULES_ITEM,
  SANITARY_RULES_ITEM,
  CARDS_ITEM,
  ATLASES_ITEM,
  MUSIC_ITEM,
} from "src/app/constatants";
import { TSelectedKeys, TSelectedLanguageKeys } from "src/app/models/Models";
import {
  SELECTED_SERIES_RESOURCE,
  SELECTED_SCIENCE_WORKS,
  SELECTED_LEGIS_DOCUMENT,
  SELECTED_BOOK,
  SELECTED_MULTI_VOLUME_BOOK,
  SELECTED_STANDART_DESCRIPTION,
  SELECTED_PART_OF_BOOK,
  SELECTED_THESIS_BOOK,
  SELECTED_PAPER_FROM_MAGAZINE,
  SELECTED_PAPER_FROM_BOOK,
  SELECTED_PAPER_FROM_VOLUME,
  SELECTED_PAPER_FROM_NEWSPAPER,
  SELECTED_PAPER_FROM_SCIENCE_WORKS,
  SELECTED_LOCAL_ELECTRONIC_RESOURCE,
  SELECTED_REMOTE_ELECTRONIC_RESOURCE,
  SELECTED_WEBSITE_RESOURCE,
  SELECTED_PAGE_FROM_WEBSITE,
  SELECTED_INTERNET_PORTAL,
  SELECTED_YEAR_BOOK,
  SELECTED_TYPICAL_PROJECT,
  SELECTED_PRICE_LIST,
  SELECTED_POSTCARD,
  SELECTED_INTERVIEW,
  SELECTED_CTALOGS_ITEM,
  SELECTED_CONSTRUCTION_RULES,
  SELECTED_SANITARY_RULES,
  SELECTED_CARDS,
  SELECTED_ATLASES,
  SELECTED_NOTES,
} from "../../../constatants/selectedOptionsConstants";
import {
  ADDITIONAL_MULTI_VOLUME_OPTIONS,
  ADDITIONAL_STANDARTS_OPTIONS,
  ADDITIONAL_BOOK_OPTIONS,
  ADDITIONAL_THESIS_OPTIONS,
  ADDITIONAL_NOTATES_OPTIONS,
  ADDITIONAL_ELECTRONIC_OPTIONS,
} from "./additionalOptions";

export const SELECTED_BOOKS_KEYS: TSelectedKeys = {
  [BOOK_ITEM]: [...SELECTED_BOOK, ...ADDITIONAL_BOOK_OPTIONS],
  [SERIES_RESOURSE_ITEM]: SELECTED_SERIES_RESOURCE,
  [SCIENCE_WORKS_ITEM]: SELECTED_SCIENCE_WORKS,
  [MULTI_VOLUME_BOOKS_ITEM]: [
    ...SELECTED_MULTI_VOLUME_BOOK.filter(({ key }) => key !== "volumeName"),
    ...ADDITIONAL_MULTI_VOLUME_OPTIONS,
  ],
  [LEGIS_DOCUMENT_ITEM]: SELECTED_LEGIS_DOCUMENT,
  [STANDART_DESCRIPTION_ITEM]: [
    ...SELECTED_STANDART_DESCRIPTION,
    ...ADDITIONAL_STANDARTS_OPTIONS,
  ],
  [PART_OF_BOOK_ITEM]: SELECTED_PART_OF_BOOK,
  [THESIS_ITEM]: [...SELECTED_THESIS_BOOK, ...ADDITIONAL_THESIS_OPTIONS],
  [ABSTRACT_THESIS_ITEM]: [
    ...SELECTED_THESIS_BOOK.filter(({ key }) => key !== "scienceCouch"),
    ...ADDITIONAL_THESIS_OPTIONS,
  ],
  [CATALOGS_ITEM]: SELECTED_CTALOGS_ITEM,
  [YEARBOOKS_ITEM]: SELECTED_YEAR_BOOK,
  [TYPICAL_PROJECT_ITEM]: SELECTED_TYPICAL_PROJECT,
  [PRICE_LIST_ITEM]: SELECTED_PRICE_LIST,
  [POSTCARD_ITEM]: SELECTED_POSTCARD,
  [INTERVIEW_ITEM]: SELECTED_INTERVIEW,
};

export const SELECTED_PAPER_KEYS: TSelectedKeys = {
  [PAPER_FROM_MAGAZINE_ITEM]: [
    ...SELECTED_PAPER_FROM_MAGAZINE,
    ...ADDITIONAL_NOTATES_OPTIONS,
  ],
  [PAPER_FROM_BOOK_ITEM]: SELECTED_PAPER_FROM_BOOK,
  [PAPER_FROM_VOLUME_ITEM]: SELECTED_PAPER_FROM_VOLUME,
  [PAPER_FROM_NEWSPAPER_ITEM]: SELECTED_PAPER_FROM_NEWSPAPER,
  [PAPER_FROM_SCIENCE_WORKS_ITEM]: [
    ...SELECTED_PAPER_FROM_SCIENCE_WORKS,
    ...ADDITIONAL_NOTATES_OPTIONS,
  ],
};

export const SELECTED_ELECTRONIC_KEYS: TSelectedKeys = {
  [LOCAL_ELECTRONIC_ITEM]: [
    ...SELECTED_LOCAL_ELECTRONIC_RESOURCE,
    ...ADDITIONAL_ELECTRONIC_OPTIONS,
  ],
  [REMOTE_ELECTRONIC_ITEM]: [
    ...SELECTED_REMOTE_ELECTRONIC_RESOURCE,
    ...ADDITIONAL_ELECTRONIC_OPTIONS,
  ],
  [WEBSITE_ITEM]: SELECTED_WEBSITE_RESOURCE,
  [PAGE_FROM_WEBSITE_ITEM]: SELECTED_PAGE_FROM_WEBSITE,
  [INTERNET_PORTAL_ITEM]: SELECTED_INTERNET_PORTAL,
};

export const SELECTED_RULES_AND_REGULATIONS_ITEM_KEYS: TSelectedKeys = {
  [CONSTRUCTION_RULES_ITEM]: SELECTED_CONSTRUCTION_RULES,
  [SANITARY_RULES_ITEM]: SELECTED_SANITARY_RULES,
};

export const SELECTED_CARDS_KEYS: TSelectedKeys = {
  [CARDS_ITEM]: SELECTED_CARDS,
  [ATLASES_ITEM]: SELECTED_ATLASES,
  [MUSIC_ITEM]: SELECTED_NOTES,
};

export const SELECTED_LANGUAGES_KEYS: TSelectedLanguageKeys = {
  [LANGUAGE_UA]: SIGNS_FOR_UA,
  [LANGUAGE_EN]: SIGNS_FOR_EN,
  [LANGUAGE_RU]: SIGNS_FOR_RU,
};
